site_name: PHP Chess Server
pages:
  - Chess Server for Web Apps: index.md
  - /start: start.md
  - /legal: legal.md
  - /play_lan: play-lan.md
  - /heuristics: heuristics.md
  - /undo: undo.md
  - /accept: accept.md
  - /takeback: takeback.md
  - /draw: draw.md
  - /resign: resign.md
  - /leave: leave.md
  - /rematch: rematch.md
  - /restart: restart.md
  - /stockfish: stockfish.md
  - /inbox: inbox.md
  - /online_games: online_games.md
theme: readthedocs
